### ISSUE TITLE
Music stops before my process is done

### ISSUE THREAD

**Issue by makenai** [MylesBorins/breakfast-machine#3]
I guess we need some sort of looping action!

“Dance," said the Sheep Man. "Yougottadance. Aslongasthemusicplays. Yougotta dance. Don'teventhinkwhy. Starttothink, yourfeetstop. Yourfeetstop, wegetstuck. Wegetstuck, you'restuck. Sodon'tpayanymind, nomatterhowdumb. Yougottakeepthestep. Yougottalimberup. Yougottaloosenwhatyoubolteddown. Yougottauseallyougot. Weknowyou're tired, tiredandscared. Happenstoeveryone, okay? Justdon'tletyourfeetstop.” 
― Haruki Murakami, Dance Dance Dance

**Comment by MylesBorins** [comment]
@makenai you should switch to http://github.com/thealphanerd/musa which includes looping

**Comment by makenai** [comment]
Aha! Much better option. Please to ignore the PR. :)
